### ISSUE TITLE
Authenticated MQTT

### ISSUE THREAD

**Issue by marvoh** [mouse256/arylic-mqtt#2]
Hello,

How would I add the credentials for authenticating against the MQTT server?

Best,
N

**Comment by mouse256** [comment]
Good question. I'm using unauthentiated mqtt on my local network. I'll add support for it in a next release.

**Comment by mouse256** [comment]
Added in https://github.com/mouse256/arylic-mqtt/releases/tag/v1.1.0

**Comment by marvoh** [comment]
Allow me to open this again if you do not mind. 

It does seem to try to connect but there's a new problem. 

It looks like it's trying to connect to the mqtt server on localhost (127.0.0.1) instead of the provided mqtt host IP.

Here's a snapshot of the log:

`2024-03-26 07:09:27,617 ERROR [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Can't connect to 127.0.0.1:1883: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:1883
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by mouse256** [comment]
Sure, no problem.
That's likely because the config variable `MQTT_HOST` not longer exists, it's now `MP_MESSAGING_CONNECTOR_SMALLRYE_MQTT_HOST`. Which was problably not the best idea. I'll create an update which add these shorter variables again. But in the meanwhile it should be possible to use it like this.

**Comment by mouse256** [comment]
New release v1.2.0 solves this. Configuration options are clean again

**Comment by marvoh** [comment]
Hello,

Sorry I was away from my computer for sometime. 

Thank you for the update. It seems to go past the previous version but (unfotunately) the credentials provided seem to be rejected. Here's a sample of the logs

```2024-04-11 11:49:38 2024-04-11 08:49:38,401 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with 10.0.0.5:1883 established successfully
2024-04-11 11:49:38 2024-04-11 08:49:38,407 ERROR [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection refused by the server - code: CONNECTION_REFUSED_NOT_AUTHORIZED
2024-04-11 11:49:39 2024-04-11 08:49:39,416 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with 10.0.0.5:1883 established successfully
2024-04-11 11:49:39 2024-04-11 08:49:39,420 ERROR [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection refused by the server - code: CONNECTION_REFUSED_NOT_AUTHORIZED
2024-04-11 11:49:40 2024-04-11 08:49:40,429 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with 10.0.0.5:1883 established successfully
2024-04-11 11:49:40 2024-04-11 08:49:40,431 ERROR [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection refused by the server - code: CONNECTION_REFUSED_NOT_AUTHORIZED ```

I removed authentication just to be able to test which worked well.

**Comment by mouse256** [comment]
It works fine for me (using mosquitto with authentication required)

```
MQTT_USERNAME=tom MQTT_PASSWORD=123456789 java -jar build/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-04-11 20:20:10,303 INFO  [io.sma.rea.mes.mqtt] (main) Create MQTT Client for tom:123456789@127.0.0.1:1883<>-[arylic-mqtt].
2024-04-11 20:20:10,402 INFO  [org.acm.Controller] (main) onStart
2024-04-11 20:20:10,408 INFO  [org.acm.Mqtt] (main) Init MQTT
2024-04-11 20:20:10,421 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with 127.0.0.1:1883 established successfully

```

**Comment by marvoh** [comment]
Which version of Mosquitto are you using? I'm on version 2.

**Comment by mouse256** [comment]
I'm using mosquitto 2.0.11
Do you see your username and password being picked up? It's printed out on startup (see my sample)

**Comment by marvoh** [comment]
I just checked again, it did connect, I think the image had not been updated so I deleted everything and pulled latest images and now everything it okay. 

Thank you. Looking forward the HTTP endpoints now
